services:
  whisperx-web:
    build: .
    container_name: whisperx-web
    ports:
      - "5000:5000"
    volumes:
      # Data persistence
      - ./data:/app/data
      - ./models_cache:/root/.cache
      # Optional: Mount additional audio files
      - ./audio_files:/app/audio_files:ro
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - whisperx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Redis for job queue (for future async processing)
  redis:
    image: redis:7-alpine
    container_name: whisperx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whisperx-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  whisperx-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
